/**
 * Lane identity and the scope invariants a subsession runtime must enforce.
 *
 * Contract (handed over by gaebal-gajae, 2026-08-26):
 *   one GitHub issue (or one PR) = one worktree = one branch = one GJC session,
 *   and a single branch never has two mutation owners. Independent backlog items
 *   may run in parallel without a fixed limit.
 *
 * The Discord channel id and operator mention from the older `create.sh` are NOT
 * part of this contract: they are optional observer routing for detached failure
 * notifications, so they live in `observer` and never in the spawn core.
 */

export type LaneKind = "issue" | "pr";

export type LaneSpec = {
	readonly kind: LaneKind;
	/** GitHub issue or PR number. */
	readonly number: number;
	/** Short kebab slug, used only for human readability. */
	readonly slug: string;
	readonly branch: string;
	readonly worktreePath: string;
	readonly baseRef?: string;
	/** Optional notification-only routing; never a control surface. */
	readonly observer?: LaneObserver;
};

export type LaneObserver = {
	readonly channelId?: string;
	readonly mention?: string;
};

export class LaneScopeError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "LaneScopeError";
	}
}

const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export function laneSessionName(spec: Pick<LaneSpec, "kind" | "number" | "slug">): string {
	if (!Number.isInteger(spec.number) || spec.number <= 0) {
		throw new LaneScopeError(`lane number must be a positive integer, got ${spec.number}`);
	}
	if (!SLUG_PATTERN.test(spec.slug)) {
		throw new LaneScopeError(`lane slug must be kebab-case, got "${spec.slug}"`);
	}
	return `project-${spec.kind}-${spec.number}-${spec.slug}`;
}

/**
 * Builds the supervisor's lane key.
 *
 * This is not a GJC protocol field: it is the supervisor's stable handle for a
 * lane, so it must be host-unique, survive restart/query/retire, and stay
 * tmux-safe. It is deliberately decoupled from the branch name - a branch like
 * `feat/subsession-runtime` contains a slash and would be an unsafe tmux target.
 * Work without an issue/PR number uses the `feature` form until a number exists.
 */
export function laneSessionKey(input: {
	readonly kind: LaneKind | "feature";
	readonly label: string;
	readonly number?: number;
}): string {
	const label = input.label
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "");
	if (label.length === 0) {
		throw new LaneScopeError(`lane label "${input.label}" has no usable characters`);
	}
	if (input.kind === "feature") {
		if (input.number !== undefined) {
			throw new LaneScopeError("a feature lane key must not carry an issue or PR number");
		}
		return `project-feature-${label}`;
	}
	if (!Number.isInteger(input.number) || (input.number ?? 0) <= 0) {
		throw new LaneScopeError(`a ${input.kind} lane key requires a positive number`);
	}
	return `project-${input.kind}-${input.number}-${label}`;
}

/**
 * The runtime session id is generated by GJC at launch, so the lane name is only
 * a stable external handle. Anything that assumes `name === sessionId` breaks as
 * soon as a session is recreated.
 */
export function isRuntimeSessionId(candidate: string): boolean {
	return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(candidate);
}

export type LaneClaim = {
	readonly sessionName: string;
	readonly branch: string;
	readonly worktreePath: string;
};

/**
 * Tracks which session owns mutation rights for a branch/worktree.
 *
 * Rejecting a second claim is what keeps two workers from writing the same
 * branch; re-claiming with the same session name is idempotent so a supervisor
 * restart does not lose its own lane.
 */
export class LaneRegistry {
	readonly #byBranch = new Map<string, LaneClaim>();
	readonly #byWorktree = new Map<string, LaneClaim>();

	claim(claim: LaneClaim): LaneClaim {
		const onBranch = this.#byBranch.get(claim.branch);
		if (onBranch && onBranch.sessionName !== claim.sessionName) {
			throw new LaneScopeError(
				`branch ${claim.branch} is already owned by ${onBranch.sessionName}; refusing a second mutation owner`,
			);
		}
		const onWorktree = this.#byWorktree.get(claim.worktreePath);
		if (onWorktree && onWorktree.sessionName !== claim.sessionName) {
			throw new LaneScopeError(
				`worktree ${claim.worktreePath} is already owned by ${onWorktree.sessionName}; refusing a second mutation owner`,
			);
		}
		this.#byBranch.set(claim.branch, claim);
		this.#byWorktree.set(claim.worktreePath, claim);
		return claim;
	}

	release(sessionName: string): void {
		for (const [branch, claim] of this.#byBranch) {
			if (claim.sessionName === sessionName) {
				this.#byBranch.delete(branch);
			}
		}
		for (const [worktree, claim] of this.#byWorktree) {
			if (claim.sessionName === sessionName) {
				this.#byWorktree.delete(worktree);
			}
		}
	}

	owner(branch: string): LaneClaim | undefined {
		return this.#byBranch.get(branch);
	}

	get size(): number {
		return this.#byBranch.size;
	}
}
