// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

export interface EmbeddedAddon {
	platformTag: string;
	version: string;
	executable: "way" | "way-discord";
	filename: string;
	filePath: string;
}

export const embeddedAddon: EmbeddedAddon | null = null;
