// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

export interface EmbeddedAddon {
	platformTag: string;
	version: string;
	contentHash: string;
	executable: "gajaeway" | "gajaeway-discord" | "gajaeway-telegram";
	filename: string;
	filePath: string;
}

export const embeddedAddon: EmbeddedAddon | null = null;
