/* auto-generated by NAPI-RS */
/* eslint-disable */
/** N-API handle over a real, migrated SQLite state directory. */
export declare class WayCore {
  /**
   * Opens the state directory, migrates it under SQLite WAL, and runs
   * `integrity_check` before exposing any mutation APIs. Startup also performs
   * the v1 in-daemon lease death-check before the daemon accepts work.
   */
  static open(stateDir: string): WayCore
  /**
   * Internal deterministic test seam for the ten-minute hard-cap protocol.
   * The shipped daemon always uses the fixed production cap.
   */
  static openWithTestHardCap(stateDir: string, hardHoldCapMs: number): WayCore
  get stateDir(): string
  /**
   * Starts the hardened state-directory UDS server and registers the TSFN
   * bridge callback before accepting any client request.
   */
  startRpcServer(socketPath: string, bridgeCallback: (err: null | Error, request: BridgeRequest) => void): void
  /**
   * Resolves one TypeScript bridge request. The completion payload is a JSON
   * result, or `{\"error\": ...}` for a typed bridge-side failure.
   */
  bridgeComplete(requestId: number, resultJson: string): boolean
  shutdownRpcServer(): void
  rpcBridgeStats(): RpcBridgeStats
  rpcDroppedNotificationCount(): number
  /**
   * Updates the in-memory health state exposed by the already-running RPC
   * listener. Durable failure reasons are stored separately in gateway_meta.
   */
  setRpcHealth(state: string, reason?: string | undefined | null): void
  /** Publishes live main-session state after strict resume for `way.status`. */
  setMainSessionStatus(turnState: string, followUpQueueDepth: number, verificationState: string): void
  /** Clears process-local resume facts once the hosted main session is gone. */
  resetMainSessionStatus(): void
  /** Marks journal-derived delivery as halted after a synchronous append failure. */
  setJournalDegraded(degraded: boolean): void
  /**
   * Sends a best-effort systemd STATUS notification. It is intentionally a
   * no-op when this process was not started with NOTIFY_SOCKET.
   */
  sdNotifyStatus(status: string): void
  /**
   * Sends systemd `READY=1` and STATUS after the daemon is fully usable.
   * It is a no-op when the process was not started with NOTIFY_SOCKET.
   */
  sdNotifyReady(status: string): void
  gatewayMetaRead(keys: Array<string>): GatewayMetaReadOutput
  /**
   * Applies a compare-and-set metadata update and optional journal event in
   * one SQLite WAL transaction. A false `applied` result means no write or
   * event was committed because an expected value changed.
   */
  gatewayMetaTransaction(input: GatewayMetaTransactionInput): GatewayMetaTransactionOutput
  lockAcquire(input: LockAcquireInput): LockAcquireOutput
  lockRenew(leaseId: string): LockRenewOutput
  /**
   * Returns whether this exact lease/token still owns write authority at a
   * Git step boundary. A false result is a fail-stop instruction.
   */
  lockFencingValid(leaseId: string, fencingToken: string): boolean
  /**
   * Returns durable FSM revocation notices once. The in-daemon executor owns
   * the actual child handle and confirms process-group reaping.
   */
  lockDrainRevocations(): Array<string>
  /**
   * Captures a process and process-group incarnation for an in-daemon child
   * before its lease row is created.
   */
  processIdentity(pid: number): ProcessIdentityOutput
  lockRelease(leaseId: string): LockReleaseOutput
  lockStatus(): LockStatusOutput
  lockForceRelease(leaseId: string, confirm: boolean): LockReleaseOutput
  lockQuarantineOverride(leaseId: string, confirm: boolean, acknowledgeUnverified: boolean): LockStatusOutput
  /**
   * Persists a structurally complete operator verification receipt for the
   * exact quarantined corpus lease after runtime death proof.
   */
  lockRecordQuarantineReceipt(input: LockQuarantineReceiptInput): LockQuarantineReceiptOutput
  lockClearQuarantine(verificationReceiptId: string, confirm: boolean): LockStatusOutput
  journalAppend(kind: string, payloadJson: string): JournalAppendOutput
  journalRead(cursor?: string | undefined | null, limit?: number | undefined | null): JournalReadOutput
  consumerClaim(consumerId: string, claimTtlMs?: number | undefined | null): ConsumerClaimOutput
  consumerCommit(input: ConsumerCommitInput): ConsumerCommitOutput
  consumerCursor(consumerId: string): string | null
  consumerOutbox(consumerId: string): Array<OutboxRowOutput>
  registryApplyBrokerSnapshot(input: RegistryApplyBrokerSnapshotInput): RegistrySnapshotApplyOutput
  registryList(input?: RegistryListInput | undefined | null): RegistryListOutput
  registryGet(sessionId: string): RegistryRowOutput
  registryAnnotate(input: RegistryAnnotationInput): RegistryRowOutput
  registryApplyMetadata(input: RegistryMetadataInput): RegistryRowOutput
  registryMarkMetadataUnavailable(input: RegistryMetadataUnavailableInput): RegistryRowOutput
  registryConfigureSurfaces(surfaces: Array<RegistrySurfaceInput>, observedAt?: number | undefined | null): void
  registryBindSurface(surfaceId: string, sessionId: string, observedAt?: number | undefined | null): void
  registryRegisterGatewaySession(input: RegistryGatewaySessionInput): RegistryRowOutput
  surfaceResolve(surfaceId: string): SurfaceResolutionOutput
  setReconcileStatus(input: ReconcileStatusInput): void
  idempotencyReplay(input: IdempotencyReplayInput): IdempotencyReplayOutput
  idempotencyStore(input: IdempotencyStoreInput): void
  /** Claims a corpus closure's durable intent before its Git effect begins. */
  closureOperationClaim(input: ClosureOperationClaimInput): ClosureOperationClaimOutput
  /**
   * Atomically publishes a completed corpus closure response and removes its
   * active intent only when the exact original intent still owns the key.
   */
  closureOperationFinalize(input: ClosureOperationFinalizeInput): ClosureOperationFinalizeOutput
  /** Claims a main admission's durable broker operation intent before the broker send. */
  mainAdmissionOperationClaim(input: MainAdmissionOperationClaimInput): MainAdmissionOperationClaimOutput
  /** Finalizes a broker-accepted main admission without changing its operation reference. */
  mainAdmissionOperationFinalize(input: MainAdmissionOperationFinalizeInput): MainAdmissionOperationFinalizeOutput
  /** Atomically abandons a definitively broker-rejected pre-effect admission claim. */
  mainAdmissionOperationAbandon(input: MainAdmissionOperationAbandonInput): void
  /** Returns unresolved pre-effect admissions for startup recovery only. */
  mainAdmissionOperationsPending(): Array<PendingMainAdmissionOperationOutput>
}

/** Request data delivered from Rust's TSFN into the thin TypeScript shim. */
export interface BridgeRequest {
  reqId: number
  method: string
  paramsJson: string
}

export interface ClosureOperationClaimInput {
  scope: string
  key: string
  requestJson: string
  intentJson: string
  operationJson: string
}

export interface ClosureOperationClaimOutput {
  claimed: boolean
  responseJson?: string
}

export interface ClosureOperationFinalizeInput {
  scope: string
  key: string
  requestJson: string
  intentJson: string
  responseJson: string
  operationJson: string
}

export interface ClosureOperationFinalizeOutput {
  responseJson: string
}

export interface ConsumerClaimOutput {
  claimId: string
  cursor: string
  expiresAt: number
}

export interface ConsumerCommitInput {
  consumerId: string
  claimId: string
  cursor: string
  proofs: Array<DeliveryProofInput>
}

export interface ConsumerCommitOutput {
  committedCursor: string
}

export interface DeliveryProofInput {
  seq: string
  platformMsgId?: string
  dedupeKey?: string
}

/**
 * One metadata value returned from the durable gateway state store. A missing
 * key is represented by an absent value rather than a synthetic default.
 */
export interface GatewayMetaEntry {
  key: string
  value?: string
}

/** A compare-and-set condition evaluated inside a single SQLite transaction. */
export interface GatewayMetaExpectation {
  key: string
  value: string
}

/** A durable metadata write performed by `gatewayMetaTransaction`. */
export interface GatewayMetaPut {
  key: string
  value: string
}

export interface GatewayMetaReadOutput {
  entries: Array<GatewayMetaEntry>
}

/**
 * Atomic metadata mutation used by the bootstrap, growth, and profile-approval
 * protocols. `eventKind` and `eventPayloadJson` are committed in the same WAL
 * transaction when present.
 */
export interface GatewayMetaTransactionInput {
  expected: Array<GatewayMetaExpectation>
  puts: Array<GatewayMetaPut>
  deletes: Array<string>
  eventKind?: string
  eventPayloadJson?: string
}

export interface GatewayMetaTransactionOutput {
  applied: boolean
  cursor?: string
}

/** Returns the process-local boot identity used by health probes. */
export declare function healthInfo(): HealthInfo

export interface HealthInfo {
  version: string
  bootEpoch: number
}

export interface IdempotencyReplayInput {
  scope: string
  key: string
  requestJson: string
}

export interface IdempotencyReplayOutput {
  replayed: boolean
  responseJson?: string
}

export interface IdempotencyStoreInput {
  scope: string
  key: string
  requestJson: string
  responseJson: string
}

export interface JournalAppendOutput {
  cursor: string
  seq: string
}

export interface JournalEventOutput {
  seq: string
  ts: number
  kind: string
  payloadJson: string
}

export interface JournalGapOutput {
  missingFrom: string
  missingTo: string
  resyncCursor: string
}

export interface JournalReadOutput {
  events: Array<JournalEventOutput>
  nextCursor: string
  gap?: JournalGapOutput
}

export interface LeaseOutput {
  leaseId: string
  holderKind: string
  sessionId: string
  label: string
  pid: number
  pidStartTime: string
  pgid: number
  pgidStartTime?: string
  connId?: string
  class: string
  state: string
  fencingToken: string
  expiresAt: number
}

export interface LockAcquireInput {
  label: string
  class?: string
  waitMs?: number
  ttlMs?: number
  holder: LockHolderInput
}

export interface LockAcquireOutput {
  leaseId: string
  fencingToken: string
  expiresAt: number
  queueWaitedMs: number
}

export interface LockHolderInput {
  holderKind: string
  sessionId: string
  pid: number
  pidStartTime: string
  pgid: number
  pgidStartTime?: string
  connId?: string
}

export interface LockQuarantineReceiptInput {
  leaseId: string
  corpus: string
  processInspected: boolean
  gitStatusChecked: boolean
  gitLogChecked: boolean
  gitFsckChecked: boolean
  remoteVerified: boolean
}

export interface LockQuarantineReceiptOutput {
  receiptId: string
  leaseId: string
  corpus: string
}

export interface LockReleaseOutput {
  released: boolean
  heldMs: number
}

export interface LockRenewOutput {
  expiresAt: number
}

export interface LockStatusOutput {
  held: boolean
  holder?: LeaseOutput
  expiresAt?: number
  fencingToken?: string
  queue: Array<QueueEntryOutput>
  stuck: boolean
  quarantined: boolean
}

export interface MainAdmissionOperationAbandonInput {
  scope: string
  key: string
  requestJson: string
  intentJson: string
}

export interface MainAdmissionOperationClaimInput {
  scope: string
  key: string
  requestJson: string
  intentJson: string
}

export interface MainAdmissionOperationClaimOutput {
  claimed: boolean
  responseJson?: string
}

export interface MainAdmissionOperationFinalizeInput {
  scope: string
  key: string
  requestJson: string
  intentJson: string
  responseJson: string
}

export interface MainAdmissionOperationFinalizeOutput {
  responseJson: string
}

export interface OutboxRowOutput {
  consumerId: string
  seq: string
  state: string
  platformMsgId?: string
  dedupeKey?: string
}

export interface PendingMainAdmissionOperationOutput {
  scope: string
  key: string
  requestJson: string
  intentJson: string
}

export interface ProcessIdentityOutput {
  pid: number
  pidStartTime: string
  pgid: number
  pgidStartTime?: string
}

export interface QueueEntryOutput {
  class: string
  label: string
  waitedMs: number
}

export interface ReconcileStatusInput {
  lastOkAt: number
  cycleMs: number
  driftCount: number
}

export interface RegistryAnnotationInput {
  sessionId: string
  purpose?: string
  brief?: string
  observedAt?: number
}

export interface RegistryApplyBrokerSnapshotInput {
  observedAt: number
  rows: Array<RegistryBrokerRowInput>
}

export interface RegistryBrokerRowInput {
  sessionId: string
  /** Canonical JSON for the SDK's credential-free locator object. */
  locator: string
  endpointGeneration: number
  hostIncarnation?: string
  identityProvenance?: string
  indexSeq: number
  live: boolean
  deleted: boolean
  terminalUncertain: boolean
  ambiguous: boolean
  activityState?: string
  activityAt?: number
  lastHeartbeatAt?: number
}

export interface RegistryGatewaySessionInput {
  sessionId: string
  kind: string
  purpose?: string
  brief?: string
  status: string
  surfaceId?: string
  observedAt?: number
}

export interface RegistryListInput {
  kind?: string
  status?: string
  surfaceId?: string
  limit?: number
  offset?: number
}

export interface RegistryListOutput {
  rows: Array<RegistryRowOutput>
  total: number
}

export interface RegistryMetadataInput {
  sessionId: string
  name: string
  cwd: string
  kind: string
  observedAt: number
}

export interface RegistryMetadataUnavailableInput {
  sessionId: string
  observedAt: number
}

export interface RegistryRowOutput {
  sessionId: string
  kind: string
  purpose?: string
  brief?: string
  status: string
  surfaceId?: string
  locator?: string
  endpointGeneration?: number
  hostIncarnation?: string
  identityProvenance?: string
  indexSeq?: number
  live: boolean
  deleted: boolean
  terminalUncertain: boolean
  ambiguous: boolean
  activityState?: string
  activityAt?: number
  lastHeartbeatAt?: number
  metaName?: string
  metaCwd?: string
  metaKind?: string
  metadataState: string
  metadataAt?: number
  source: string
  createdAt: number
  lastSeenAt?: number
  closedAt?: number
  registryRev: number
  quarantined: boolean
}

export interface RegistrySnapshotApplyOutput {
  newSessionIds: Array<string>
  changedSessionIds: Array<string>
  changedIndexSeqSessionIds: Array<string>
  driftCount: number
}

export interface RegistrySurfaceInput {
  surfaceId: string
  platform: string
  kind: string
  isOwnerSurface: boolean
}

export interface RpcBridgeStats {
  inFlight: number
  overloads: number
  timeouts: number
  duplicateCompletions: number
  lateCompletions: number
  queueClosed: number
}

export interface SurfaceResolutionOutput {
  surface: RegistrySurfaceInput
  sessionId?: string
  quarantined: boolean
}
