/* auto-generated by NAPI-RS */
/* eslint-disable */
/** N-API handle over a real, migrated SQLite state directory. */
export declare class WayCore {
  /**
   * Opens the state directory, migrates it under SQLite WAL, and runs
   * `integrity_check` before exposing any mutation APIs.
   */
  static open(stateDir: string): WayCore
  get stateDir(): string
  lockAcquire(input: LockAcquireInput): LockAcquireOutput
  lockRenew(leaseId: string): LockRenewOutput
  lockRelease(leaseId: string): LockReleaseOutput
  lockStatus(): LockStatusOutput
  lockForceRelease(leaseId: string, confirm: boolean): LockReleaseOutput
  lockQuarantineOverride(leaseId: string, confirm: boolean, acknowledgeUnverified: boolean): LockStatusOutput
  lockClearQuarantine(verificationReceiptId: string, confirm: boolean): LockStatusOutput
  journalAppend(kind: string, payloadJson: string): JournalAppendOutput
  journalRead(cursor?: string | undefined | null, limit?: number | undefined | null): JournalReadOutput
  consumerClaim(consumerId: string, claimTtlMs?: number | undefined | null): ConsumerClaimOutput
  consumerCommit(input: ConsumerCommitInput): ConsumerCommitOutput
  consumerCursor(consumerId: string): string | null
  consumerOutbox(consumerId: string): Array<OutboxRowOutput>
  idempotencyReplay(input: IdempotencyReplayInput): IdempotencyReplayOutput
  idempotencyStore(input: IdempotencyStoreInput): void
}

export interface ConsumerClaimOutput {
  claimId: string
  cursor: string
  expiresAt: number
}

export interface ConsumerCommitInput {
  consumerId: string
  claimId: string
  cursor: string
  proofs: Array<DeliveryProofInput>
}

export interface ConsumerCommitOutput {
  committedCursor: string
}

export interface DeliveryProofInput {
  seq: string
  platformMsgId?: string
  dedupeKey?: string
}

/** Returns the process-local boot identity used by the P0 health probe. */
export declare function healthInfo(): HealthInfo

export interface HealthInfo {
  version: string
  bootEpoch: number
}

export interface IdempotencyReplayInput {
  scope: string
  key: string
  requestJson: string
}

export interface IdempotencyReplayOutput {
  replayed: boolean
  responseJson?: string
}

export interface IdempotencyStoreInput {
  scope: string
  key: string
  requestJson: string
  responseJson: string
}

export interface JournalAppendOutput {
  cursor: string
  seq: string
}

export interface JournalEventOutput {
  seq: string
  ts: number
  kind: string
  payloadJson: string
}

export interface JournalGapOutput {
  missingFrom: string
  missingTo: string
  resyncCursor: string
}

export interface JournalReadOutput {
  events: Array<JournalEventOutput>
  nextCursor: string
  gap?: JournalGapOutput
}

export interface LeaseOutput {
  leaseId: string
  holderKind: string
  sessionId: string
  label: string
  pid: number
  pidStartTime: string
  pgid: number
  pgidStartTime?: string
  connId?: string
  class: string
  state: string
  fencingToken: string
  expiresAt: number
}

export interface LockAcquireInput {
  label: string
  class?: string
  waitMs?: number
  ttlMs?: number
  holder: LockHolderInput
}

export interface LockAcquireOutput {
  leaseId: string
  fencingToken: string
  expiresAt: number
  queueWaitedMs: number
}

export interface LockHolderInput {
  holderKind: string
  sessionId: string
  pid: number
  pidStartTime: string
  pgid: number
  pgidStartTime?: string
  connId?: string
}

export interface LockReleaseOutput {
  released: boolean
  heldMs: number
}

export interface LockRenewOutput {
  expiresAt: number
}

export interface LockStatusOutput {
  held: boolean
  holder?: LeaseOutput
  expiresAt?: number
  fencingToken?: string
  queue: Array<QueueEntryOutput>
  stuck: boolean
  quarantined: boolean
}

export interface OutboxRowOutput {
  consumerId: string
  seq: string
  state: string
  platformMsgId?: string
  dedupeKey?: string
}

export interface QueueEntryOutput {
  class: string
  label: string
  waitedMs: number
}
