/* auto-generated by NAPI-RS */
/* eslint-disable */
/** P0 handle proving that TypeScript owns one stable `WayCore` N-API surface. */
export declare class WayCore {
  /**
   * Opens a future state store. P0 records the requested directory only;
   * migrations and SQLite ownership arrive in P1.
   */
  static open(stateDir: string): WayCore
  get stateDir(): string
}

/** Returns the process-local boot identity used by the P0 health probe. */
export declare function healthInfo(): HealthInfo

export interface HealthInfo {
  version: string
  bootEpoch: number
}
