import * as fs from "node:fs/promises";
import * as path from "node:path";
import { createRequire } from "node:module";

const repoRoot = path.join(import.meta.dir, "..");
const nativeDir = path.join(repoRoot, "native");
const outputPath = path.join(nativeDir, "embedded-addon.ts");
const packageJsonPath = path.join(repoRoot, "package.json");
const allowedExecutables = new Set(["way", "way-discord"]);
const requiredAddonExports = ["healthInfo", "WayCore"] as const;

const stubContent = `// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY\n// See scripts/embed-native.ts\n\nexport interface EmbeddedAddon {\n\tplatformTag: string;\n\tversion: string;\n\texecutable: "way" | "way-discord";\n\tfilename: string;\n\tfilePath: string;\n}\n\nexport const embeddedAddon: EmbeddedAddon | null = null;\n`;

function parseExecutable(): "way" | "way-discord" {
	const positional = process.argv.find(argument => argument.startsWith("--for="))?.slice("--for=".length);
	const flagIndex = process.argv.indexOf("--for");
	const executable = positional ?? (flagIndex >= 0 ? process.argv[flagIndex + 1] : undefined);
	if (!executable || !allowedExecutables.has(executable)) {
		throw new Error("embed-native requires --for way or --for way-discord so both standalone executables are guarded.");
	}
	return executable as "way" | "way-discord";
}

function missingRequiredAddonExports(bindings: Record<string, unknown>): string[] {
	return requiredAddonExports.filter(symbol => typeof bindings[symbol] !== "function");
}

async function embedNative(): Promise<void> {
	if (process.argv.includes("--reset")) {
		await fs.writeFile(outputPath, stubContent);
		return;
	}

	const executable = parseExecutable();
	const targetPlatform = Bun.env.TARGET_PLATFORM || process.platform;
	const targetArch = Bun.env.TARGET_ARCH || process.arch;
	const platformTag = `${targetPlatform}-${targetArch}`;
	const filename = `way_core.${platformTag}.node`;
	const addonPath = path.join(nativeDir, filename);
	try {
		await fs.access(addonPath);
	} catch {
		throw new Error(`No native addon found for ${platformTag}: expected ${addonPath}. Run bun scripts/build-native.ts first.`);
	}

	if (platformTag === `${process.platform}-${process.arch}`) {
		const bindings = createRequire(import.meta.url)(addonPath) as Record<string, unknown>;
		const missingExports = missingRequiredAddonExports(bindings);
		if (missingExports.length > 0) {
			throw new Error(`Native addon ${filename} is missing required exports: ${missingExports.join(", ")}.`);
		}
	}

	const packageJson = (await Bun.file(packageJsonPath).json()) as { version: string };
	const content = `// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY\n// See scripts/embed-native.ts\n\nimport addonPath from ${JSON.stringify(`./${filename}`)} with { type: "file" };\n\nexport interface EmbeddedAddon {\n\tplatformTag: string;\n\tversion: string;\n\texecutable: "way" | "way-discord";\n\tfilename: string;\n\tfilePath: string;\n}\n\nexport const embeddedAddon: EmbeddedAddon = {\n\tplatformTag: ${JSON.stringify(platformTag)},\n\tversion: ${JSON.stringify(packageJson.version)},\n\texecutable: ${JSON.stringify(executable)},\n\tfilename: ${JSON.stringify(filename)},\n\tfilePath: addonPath,\n};\n`;
	await fs.writeFile(outputPath, content);
}

if (import.meta.main) {
	await embedNative();
}
